services:
  postgres:
    image: 'postgres:16-alpine'
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - anaccount-network
    ports:
      - "5432"
    labels:
      - "org.springframework.boot.service-connection=postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    restart: unless-stopped
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  anaccount-network:
    driver: bridge